//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemSystem { get; set; }
        public decimal ItemPrice { get; set; }
        public int ItemQty { get; set; }
        public string ItemContract { get; set; }
        public string ItemDescription { get; set; }
        public System.DateTime ItemCreatedDate { get; set; }
        public Nullable<int> ItemTest { get; set; }
    }
}
